@startuml

hide empty members
hide circle

Marco -- Weather: < Afecta
Marco -- Amedio: < Afecta

Marco -r- Distance: > Avanza

Distance -r- Mother: < Avanza

Time -- Journey: > Pasa

Journey -- Marco

Journey .. Distance: < while Distancia > 0

@enduml